/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as ProjectsImport } from './routes/projects'
import { Route as ProjectFormImport } from './routes/project-form'
import { Route as CommandsImport } from './routes/commands'
import { Route as CommandFormImport } from './routes/command-form'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const ProjectFormRoute = ProjectFormImport.update({
  id: '/project-form',
  path: '/project-form',
  getParentRoute: () => rootRoute,
} as any)

const CommandsRoute = CommandsImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRoute,
} as any)

const CommandFormRoute = CommandFormImport.update({
  id: '/command-form',
  path: '/command-form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/command-form': {
      id: '/command-form'
      path: '/command-form'
      fullPath: '/command-form'
      preLoaderRoute: typeof CommandFormImport
      parentRoute: typeof rootRoute
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsImport
      parentRoute: typeof rootRoute
    }
    '/project-form': {
      id: '/project-form'
      path: '/project-form'
      fullPath: '/project-form'
      preLoaderRoute: typeof ProjectFormImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-form': typeof CommandFormRoute
  '/commands': typeof CommandsRoute
  '/project-form': typeof ProjectFormRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-form': typeof CommandFormRoute
  '/commands': typeof CommandsRoute
  '/project-form': typeof ProjectFormRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/command-form': typeof CommandFormRoute
  '/commands': typeof CommandsRoute
  '/project-form': typeof ProjectFormRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command-form'
    | '/commands'
    | '/project-form'
    | '/projects'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-form'
    | '/commands'
    | '/project-form'
    | '/projects'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/command-form'
    | '/commands'
    | '/project-form'
    | '/projects'
    | '/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandFormRoute: typeof CommandFormRoute
  CommandsRoute: typeof CommandsRoute
  ProjectFormRoute: typeof ProjectFormRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandFormRoute: CommandFormRoute,
  CommandsRoute: CommandsRoute,
  ProjectFormRoute: ProjectFormRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/command-form",
        "/commands",
        "/project-form",
        "/projects",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/command-form": {
      "filePath": "command-form.tsx"
    },
    "/commands": {
      "filePath": "commands.tsx"
    },
    "/project-form": {
      "filePath": "project-form.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
